const BOX={width:700,height:460};
const lessons=[
  {id:'circle-01',module:'circle',title:'円のひみつ 1',meta:'同じ長さの点を集めよう',prompt:'黄色の点から、青い棒と同じ長さのところに 点をうとう。',reflectionPrompt:'黄色の点から同じ長さのところに点を打つと、どんな形になった？'},
  {id:'sphere-01',module:'sphere',title:'球のひみつ',meta:'回して、かげを集めよう',prompt:'球をいろいろな向きに回して、見えたかげをスタンプしよう。',reflectionPrompt:'球をどの向きから見ても、かげの形はどうなった？'}
];
const palettes=[{bg:'#16002f',point:'#ffe600',arm:'#21f3c4',text:'#fff'},{bg:'#ff145b',point:'#00ffe1',arm:'#1700ff',text:'#fff'},{bg:'#00d9a6',point:'#5c00ff',arm:'#ffea00',text:'#102a2b'},{bg:'#ff6a00',point:'#00eaff',arm:'#1900ff',text:'#fff'}];
const initialGeometry=()=>({center:{x:350,y:230},radiusPoint:{x:500,y:230}}); const app=document.querySelector('#app');
const stampColors=['#ff4f87','#6c5ce7','#00a884','#ff8a00','#1687d9','#d23fb8'];
const sphereFeatures=[[-.72,-.35,.60],[-.28,-.62,.73],[.20,-.48,.85],[.64,-.28,.72],[-.54,.12,.83],[-.08,.02,.99],[.48,.12,.87],[-.72,.48,.50],[-.25,.54,.80],[.28,.58,.76],[.70,.40,.58],[.05,.78,.55]];
const state={screen:'home',lesson:lessons[0],activeTool:'move',reflection:'',helpOpen:false,geometry:initialGeometry(),dots:[],strokes:[],history:[],palette:palettes[0],completionTimer:null,lastPlacedAt:0,sphere:{yaw:.25,pitch:-.18},stamps:[]};
let armDrag=null;
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v)); const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y); const copyGeometry=()=>JSON.parse(JSON.stringify(state.geometry)); const escapeHtml=v=>v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function render(){app.innerHTML={home:renderHome,intro:renderIntro,work:renderWork,summary:renderSummary}[state.screen]();bindEvents();}
function renderHome(){return `<section class="app-shell home"><div><p class="eyebrow">さんすう</p><h1>図形のへんしん<br>実験室</h1><p class="lead">うごかして、みつけよう。</p></div><div class="lesson-grid">${lessons.map(l=>`<button class="lesson-card" data-action="open-lesson" data-lesson-id="${l.id}"><span class="lesson-card__icon">${l.module==='sphere'?'●':'○'}</span><span class="lesson-card__title">${l.title}</span><span class="lesson-card__meta">${l.meta}</span></button>`).join('')}</div></section>`;}
function renderIntro(){return `<section class="app-shell intro"><div class="topbar"><button class="back" data-action="go-home">← もどる</button></div><div class="intro__body"><p class="eyebrow">さんすう　円と球</p><h2>${state.lesson.title}</h2><p class="prompt">${state.lesson.prompt}</p></div><button class="primary" data-action="start-work">はじめる</button></section>`;}
function workHeader(){return `<div class="topbar"><button class="back" data-action="go-intro">← もどる</button><div class="topbar__actions"><button class="next" data-action="save-png">ほぞん</button><button class="next" data-action="go-summary">まとめへ</button><button class="help" data-action="open-help">?</button></div></div><p class="work__question">${state.lesson.prompt}</p>`;}
function renderWork(){return state.lesson.module==='sphere'?renderSphereWork():renderCircleWork();}
function renderCircleWork(){const c=state.geometry.center,p=state.geometry.radiusPoint,dots=state.dots.map(d=>`<circle class="placed-dot" cx="${d.x}" cy="${d.y}" r="9"/>`).join('');const hint=state.activeTool==='move'?`<div class="enter-hint"><strong>ENTER</strong><span>で 点をうつ</span></div><p class="stage__count">${state.dots.length}こ</p>`:'<p class="stage__hint">ペンで しるしや ことばを かこう。</p>';return `<section class="app-shell work psychedelic" style="--psy-bg:${state.palette.bg};--psy-point:${state.palette.point};--psy-arm:${state.palette.arm};--psy-text:${state.palette.text}">${workHeader()}<div class="stage stage--${state.activeTool}" id="stage"><svg class="stage__svg" id="geometry-svg" viewBox="0 0 700 460">${dots}<line class="radius-arm" x1="${c.x}" y1="${c.y}" x2="${p.x}" y2="${p.y}"/><circle class="handle handle--centre" cx="${c.x}" cy="${c.y}" r="16"/><circle class="handle handle--radius" cx="${p.x}" cy="${p.y}" r="17"/></svg><canvas class="stage__ink" id="ink-canvas"></canvas>${hint}</div><nav class="tool-dock"><button aria-pressed="${state.activeTool==='move'}" data-action="tool" data-tool="move">うごかす</button><button aria-pressed="${state.activeTool==='pen'}" data-action="tool" data-tool="pen">かく</button><button data-action="undo">もどす</button></nav>${helpDialog('棒を動かして、Enterかタップで点をうとう。')}</section>`;}
function renderSphereWork(){const features=sphereFeatures.map((v,i)=>`<circle class="sphere-feature sphere-feature--${i%3}" data-vector="${v.join(',')}" r="18"/>`).join('');const stamps=state.stamps.map((s,i)=>`<div class="shadow-stamp" style="--stamp:${s.color}" aria-label="${i+1}このかげ"><span>${i+1}</span></div>`).join('');return `<section class="app-shell work sphere-work">${workHeader()}<div class="sphere-stage" id="stage"><svg class="sphere-svg" id="sphere-svg" viewBox="0 0 700 460" role="img" aria-label="指で回せる、模様と陰影のある球"><defs><radialGradient id="ball-light" cx="30%" cy="22%" r="78%"><stop offset="0" stop-color="#fff9c9"/><stop offset=".2" stop-color="#71e1d0"/><stop offset=".62" stop-color="#168fa2"/><stop offset="1" stop-color="#073852"/></radialGradient><radialGradient id="shine" cx="32%" cy="25%" r="70%"><stop offset="0" stop-color="#fff" stop-opacity=".88"/><stop offset=".25" stop-color="#fff" stop-opacity=".12"/><stop offset=".75" stop-color="#001d35" stop-opacity="0"/><stop offset="1" stop-color="#001322" stop-opacity=".72"/></radialGradient><filter id="blur"><feGaussianBlur stdDeviation="10"/></filter><clipPath id="ball-clip"><circle cx="350" cy="208" r="142"/></clipPath></defs><ellipse class="ball-shadow" cx="370" cy="382" rx="150" ry="27" filter="url(#blur)"/><circle class="ball-base" cx="350" cy="208" r="142"/><g clip-path="url(#ball-clip)">${features}<path class="sphere-band" id="sphere-band"/></g><circle class="ball-shading" cx="350" cy="208" r="142"/><ellipse class="ball-glint" cx="304" cy="154" rx="34" ry="21" transform="rotate(-35 304 154)"/><path class="turn-arrow" d="M190 100 C250 34 446 28 516 98"/><path class="turn-arrow-head" d="m501 77 18 22-28 5"/></svg><p class="sphere-instruction"><strong>ゆびで ぐるぐる</strong><span>模様のうごきを見よう</span></p><div class="stamp-tray"><p>あつめた かげ <strong>${state.stamps.length}こ</strong></p><div class="stamp-list">${stamps||'<span class="stamp-empty">まだないよ</span>'}</div></div></div><nav class="tool-dock"><button aria-pressed="true" data-action="tool" data-tool="move">まわす</button><button class="stamp-action" data-action="stamp-shadow">かげをスタンプ</button><button data-action="undo">もどす</button></nav>${helpDialog('球を指でぐるぐる回そう。向きを変えたら「かげをスタンプ」を押して、形をくらべよう。')}</section>`;}
function helpDialog(message){return state.helpOpen?`<div class="dialog"><div class="dialog__panel"><h2>つかいかた</h2><p>${message}</p><button class="primary" data-action="close-help">わかった</button></div></div>`:'';}
function renderSummary(){return `<section class="app-shell summary"><div class="topbar"><button class="back" data-action="go-work">← もどる</button></div><div class="summary__body"><p class="eyebrow">まとめ</p><h2>分かったことを<br>書こう</h2><p class="prompt">${state.lesson.reflectionPrompt}</p><textarea id="reflection" maxlength="240" placeholder="たとえば、中心から…">${escapeHtml(state.reflection)}</textarea></div><div class="summary__actions"><button class="primary" data-action="finish">おわる</button></div></section>`;}
function bindEvents(){app.querySelectorAll('[data-action]').forEach(e=>e.addEventListener('click',()=>handleAction(e.dataset)));const r=document.querySelector('#reflection');if(r)r.addEventListener('input',e=>state.reflection=e.target.value);if(state.screen==='work')setupWorkSurface();}
function setupWorkSurface(){if(state.lesson.module==='sphere'){setupSphere();return;}const svg=document.querySelector('#geometry-svg'),canvas=document.querySelector('#ink-canvas');resizeAndDrawInk(canvas);if(state.activeTool!=='move'){canvas.addEventListener('pointerdown',e=>beginInkStroke(e,canvas));return;}svg.addEventListener('pointerdown',e=>{e.preventDefault();const q=svgPoint(e,svg);armDrag=distance(q,state.geometry.center)<34?'centre':distance(q,state.geometry.radiusPoint)<34?'radius':'rotate';armMove(q,svg);if(svg.setPointerCapture)svg.setPointerCapture(e.pointerId);});svg.addEventListener('pointermove',e=>{if(armDrag||!e.buttons)armMove(svgPoint(e,svg),svg);});svg.addEventListener('pointerup',()=>{if(armDrag){armDrag=null;placeDot();}});svg.addEventListener('pointercancel',()=>{armDrag=null;});}
function rotateVector([x,y,z]){const cy=Math.cos(state.sphere.yaw),sy=Math.sin(state.sphere.yaw),cp=Math.cos(state.sphere.pitch),sp=Math.sin(state.sphere.pitch),x1=x*cy+z*sy,z1=-x*sy+z*cy;return [x1,y*cp-z1*sp,y*sp+z1*cp];}
function updateSphereVisual(){document.querySelectorAll('.sphere-feature').forEach(el=>{const [x,y,z]=rotateVector(el.dataset.vector.split(',').map(Number)),depth=clamp((z+1)/2,0,1);el.setAttribute('cx',350+x*132);el.setAttribute('cy',208+y*132);el.setAttribute('r',10+depth*16);el.style.opacity=z<-.12?0:(.35+depth*.65);});const points=[];for(let i=0;i<=44;i++){const a=i/44*Math.PI*2,v=rotateVector([Math.cos(a),0,Math.sin(a)]);if(v[2]>-.05)points.push(`${points.length?'L':'M'} ${350+v[0]*139} ${208+v[1]*139}`);}const band=document.querySelector('#sphere-band');if(band)band.setAttribute('d',points.join(' '));}
function setupSphere(){const svg=document.querySelector('#sphere-svg');updateSphereVisual();let last=null,moved=false;svg.addEventListener('pointerdown',e=>{e.preventDefault();remember();last={x:e.clientX,y:e.clientY};moved=false;if(svg.setPointerCapture)svg.setPointerCapture(e.pointerId);});svg.addEventListener('pointermove',e=>{if(!last)return;const dx=e.clientX-last.x,dy=e.clientY-last.y;if(Math.abs(dx)+Math.abs(dy)>1)moved=true;state.sphere.yaw+=dx*.012;state.sphere.pitch=clamp(state.sphere.pitch-dy*.009,-1.15,1.15);last={x:e.clientX,y:e.clientY};updateSphereVisual();});const end=()=>{last=null;if(moved)render();};svg.addEventListener('pointerup',end);svg.addEventListener('pointercancel',end);}
/* 指・マウスの位置をSVGの論理座標へ。viewBox は等比（meet）で拡大縮小＋余白が
   出るので、実スケールと余白を引いてから変換する（x/y を別々に伸ばすと
   指と棒がずれる） */
function svgPoint(e,svg){const r=svg.getBoundingClientRect(),s=Math.min(r.width/700,r.height/460),ox=(r.width-700*s)/2,oy=(r.height-460*s)/2;return{x:clamp((e.clientX-r.left-ox)/s,0,700),y:clamp((e.clientY-r.top-oy)/s,0,460)};}
/* 押した場所で役割を分ける：黄色（中心）はそのまま動かす、青（先）は半径を
   伸ばし縮め、それ以外は棒をその方向へ向ける。 */
function armMove(q,svg){const c=state.geometry.center,p=state.geometry.radiusPoint;
  if(armDrag==='centre'){state.geometry.radiusPoint={x:p.x+q.x-c.x,y:p.y+q.y-c.y};state.geometry.center={x:q.x,y:q.y};}
  else if(armDrag==='radius'){const dx=q.x-c.x,dy=q.y-c.y,l=Math.hypot(dx,dy)||1,rad=clamp(l,40,330);state.geometry.radiusPoint={x:c.x+dx/l*rad,y:c.y+dy/l*rad};}
  else{const dx=q.x-c.x,dy=q.y-c.y,l=Math.hypot(dx,dy);if(l<10)return;const rad=distance(c,p);state.geometry.radiusPoint={x:c.x+dx/l*rad,y:c.y+dy/l*rad};}
  const nc=state.geometry.center,np=state.geometry.radiusPoint,a=svg.querySelector('.radius-arm'),hr=svg.querySelector('.handle--radius'),hc=svg.querySelector('.handle--centre');
  a.setAttribute('x1',nc.x);a.setAttribute('y1',nc.y);a.setAttribute('x2',np.x);a.setAttribute('y2',np.y);hr.setAttribute('cx',np.x);hr.setAttribute('cy',np.y);hc.setAttribute('cx',nc.x);hc.setAttribute('cy',nc.y);}
function remember(){state.history.push({geometry:copyGeometry(),dots:state.dots.map(d=>({...d})),strokes:state.strokes.length,sphere:{...state.sphere},stamps:state.stamps.map(s=>({...s}))});if(state.history.length>20)state.history.shift();}
function placeDot(){const now=performance.now();if(now-state.lastPlacedAt<80)return;state.lastPlacedAt=now;const p=state.geometry.radiusPoint;if(state.dots.some(d=>distance(d,p)<22))return;remember();state.dots.push({x:p.x,y:p.y});if(state.dots.length>=18&&new Set(state.dots.map(d=>Math.floor((((Math.atan2(d.y-state.geometry.center.y,d.x-state.geometry.center.x)+Math.PI*2)%(Math.PI*2))/(Math.PI*2))*18))).size>=16)schedulePaletteChange();render();}
function schedulePaletteChange(){if(state.completionTimer)return;state.completionTimer=setTimeout(()=>{state.completionTimer=null;if(state.screen!=='work'||state.lesson.module!=='circle')return;const choices=palettes.filter(p=>p.bg!==state.palette.bg);state.palette=choices[Math.floor(Math.random()*choices.length)];const r=95+Math.random()*75;state.geometry.radiusPoint={x:state.geometry.center.x+r,y:state.geometry.center.y};state.dots=[];render();},700);}
function beginInkStroke(e,c){e.preventDefault();remember();const st=[];const add=x=>{const r=c.getBoundingClientRect();st.push({x:x.clientX-r.left,y:x.clientY-r.top});drawInk(c,st)};add(e);if(c.setPointerCapture)c.setPointerCapture(e.pointerId);const move=x=>add(x);const up=()=>{state.strokes.push(st);window.removeEventListener('pointermove',move);render()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});}
function resizeAndDrawInk(c){const s=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=Math.max(1,r.width*s);c.height=Math.max(1,r.height*s);c.getContext('2d').setTransform(s,0,0,s,0,0);drawInk(c);}
function drawInk(c,current=[]){const x=c.getContext('2d'),r=c.getBoundingClientRect();x.clearRect(0,0,r.width,r.height);x.lineCap='round';x.lineWidth=4;x.strokeStyle='#24343b';[...state.strokes,current].forEach(st=>{if(!st.length)return;x.beginPath();st.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.stroke();});}
function undo(){const p=state.history.pop();if(!p)return;state.geometry=p.geometry;state.dots=p.dots;state.strokes=state.strokes.slice(0,p.strokes);state.sphere=p.sphere||state.sphere;state.stamps=p.stamps||state.stamps;render();}
function stampShadow(){remember();const color=stampColors[state.stamps.length%stampColors.length];state.stamps.push({yaw:state.sphere.yaw,pitch:state.sphere.pitch,color});if(state.stamps.length>12)state.stamps.shift();render();}
/* 図形と手書きを1枚のPNGとして保存。いま出ているSVGをそのまま写すので、
   点・棒・球の見た目が紙そのまま残る（docs/spec にある Phase 3 の保存）。 */
function savePng(){const svg=document.querySelector('#stage svg');if(!svg)return;
  const ink=document.querySelector('#ink-canvas'),r=svg.getBoundingClientRect(),clone=svg.cloneNode(true);
  clone.setAttribute('width',r.width);clone.setAttribute('height',r.height);
  /* 単体の画像にするので、CSSから計算した色・線を属性として書き写す */
  const src=svg.querySelectorAll('*'),dst=clone.querySelectorAll('*');
  src.forEach((el,i)=>{const cs=getComputedStyle(el);for(const p of['fill','fill-opacity','stroke','stroke-width','stroke-linecap','stroke-linejoin','stroke-dasharray','stroke-dashoffset','opacity','filter'])dst[i].setAttribute(p,cs.getPropertyValue(p));});
  const img=new Image();
  img.onload=()=>{const cv=document.createElement('canvas'),sc=2;cv.width=r.width*sc;cv.height=r.height*sc;const x=cv.getContext('2d');
    const bg=getComputedStyle(svg.parentElement).backgroundColor;
    x.fillStyle=(bg==='rgba(0, 0, 0, 0)'||bg==='transparent')?'#f7f5ef':bg;
    x.fillRect(0,0,cv.width,cv.height);x.drawImage(img,0,0,cv.width,cv.height);
    if(ink)x.drawImage(ink,0,0,cv.width,cv.height);
    cv.toBlob(b=>{if(!b)return;const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=state.lesson.id+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),4000);});};
  img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(clone));}
function handleAction(d){switch(d.action){case'open-lesson':state.lesson=lessons.find(l=>l.id===d.lessonId)||lessons[0];state.activeTool='move';state.reflection='';state.history=[];state.dots=[];state.strokes=[];state.stamps=[];state.geometry=initialGeometry();state.palette=palettes[0];state.sphere={yaw:.25,pitch:-.18};if(state.completionTimer){clearTimeout(state.completionTimer);state.completionTimer=null;}state.screen='intro';break;case'go-home':state.screen='home';break;case'go-intro':state.screen='intro';break;case'start-work':state.screen='work';break;case'go-work':state.screen='work';break;case'go-summary':state.screen='summary';break;case'tool':state.activeTool=d.tool;break;case'stamp-shadow':stampShadow();return;case'save-png':savePng();return;case'undo':undo();return;case'open-help':state.helpOpen=true;break;case'close-help':state.helpOpen=false;break;case'finish':state.screen='home';break;default:return;}render();}
document.addEventListener('keydown',e=>{if(state.screen!=='work'||state.lesson.module!=='circle'||state.activeTool!=='move'||state.helpOpen||e.repeat)return;const safe=e.key==='Enter'||e.key===' '||e.code==='NumpadEnter'||(e.key.length===1&&!e.ctrlKey&&!e.metaKey&&!e.altKey);if(safe){e.preventDefault();placeDot();}});render();
