const BOX={width:700,height:460};
const lessons=[{id:'circle-01',title:'円のひみつ 1',meta:'同じ長さの点を集めよう',prompt:'黄色の点から、青い棒と同じ長さのところに 点をうとう。',reflectionPrompt:'黄色の点から同じ長さのところに点を打つと、どんな形になった？'}];
const palettes=[{bg:'#16002f',point:'#ffe600',arm:'#21f3c4',text:'#fff'},{bg:'#ff145b',point:'#00ffe1',arm:'#1700ff',text:'#fff'},{bg:'#00d9a6',point:'#5c00ff',arm:'#ffea00',text:'#102a2b'},{bg:'#ff6a00',point:'#00eaff',arm:'#1900ff',text:'#fff'}];
const initialGeometry=()=>({center:{x:350,y:230},radiusPoint:{x:500,y:230}}); const app=document.querySelector('#app');
const state={screen:'home',lesson:lessons[0],activeTool:'move',reflection:'',helpOpen:false,geometry:initialGeometry(),dots:[],strokes:[],history:[],palette:palettes[0],completionTimer:null,lastPlacedAt:0};
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v)); const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y); const copyGeometry=()=>JSON.parse(JSON.stringify(state.geometry)); const escapeHtml=v=>v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function render(){app.innerHTML={home:renderHome,intro:renderIntro,work:renderWork,summary:renderSummary}[state.screen]();bindEvents();}
function renderHome(){return `<section class="app-shell home"><div><p class="eyebrow">さんすう</p><h1>図形のへんしん<br>実験室</h1><p class="lead">うごかして、みつけよう。</p></div><div>${lessons.map(l=>`<button class="lesson-card" data-action="open-lesson" data-lesson-id="${l.id}"><span class="lesson-card__icon">○</span><span class="lesson-card__title">${l.title}</span><span class="lesson-card__meta">${l.meta}</span></button>`).join('')}</div></section>`;}
function renderIntro(){return `<section class="app-shell intro"><div class="topbar"><button class="back" data-action="go-home">← もどる</button></div><div class="intro__body"><p class="eyebrow">さんすう　円</p><h2>${state.lesson.title}</h2><p class="prompt">${state.lesson.prompt}</p></div><button class="primary" data-action="start-work">はじめる</button></section>`;}
function renderWork(){const c=state.geometry.center,p=state.geometry.radiusPoint,dots=state.dots.map(d=>`<circle class="placed-dot" cx="${d.x}" cy="${d.y}" r="9"/>`).join('');const hint=state.activeTool==='move'?`<div class="enter-hint"><strong>ENTER</strong><span>で 点をうつ</span></div><p class="stage__count">${state.dots.length}こ</p>`:'<p class="stage__hint">ペンで しるしや ことばを かこう。</p>';return `<section class="app-shell work psychedelic" style="--psy-bg:${state.palette.bg};--psy-point:${state.palette.point};--psy-arm:${state.palette.arm};--psy-text:${state.palette.text}"><div class="topbar"><button class="back" data-action="go-intro">← もどる</button><div class="topbar__actions"><button class="next" data-action="go-summary">まとめへ</button><button class="help" data-action="open-help">?</button></div></div><p class="work__question">${state.lesson.prompt}</p><div class="stage stage--${state.activeTool}" id="stage"><svg class="stage__svg" id="geometry-svg" viewBox="0 0 700 460">${dots}<line class="radius-arm" x1="${c.x}" y1="${c.y}" x2="${p.x}" y2="${p.y}"/><circle class="handle handle--centre" cx="${c.x}" cy="${c.y}" r="16"/><circle class="handle handle--radius" cx="${p.x}" cy="${p.y}" r="17"/></svg><canvas class="stage__ink" id="ink-canvas"></canvas>${hint}</div><nav class="tool-dock"><button aria-pressed="${state.activeTool==='move'}" data-action="tool" data-tool="move">うごかす</button><button aria-pressed="${state.activeTool==='pen'}" data-action="tool" data-tool="pen">かく</button><button data-action="undo">もどす</button></nav>${state.helpOpen?'<div class="dialog"><div class="dialog__panel"><h2>つかいかた</h2><p>棒を動かして、Enterかタップで点をうとう。</p><button class="primary" data-action="close-help">わかった</button></div></div>':''}</section>`;}
function renderSummary(){return `<section class="app-shell summary"><div class="topbar"><button class="back" data-action="go-work">← もどる</button></div><div class="summary__body"><p class="eyebrow">まとめ</p><h2>分かったことを<br>書こう</h2><p class="prompt">${state.lesson.reflectionPrompt}</p><textarea id="reflection" maxlength="240" placeholder="たとえば、中心から…">${escapeHtml(state.reflection)}</textarea></div><div class="summary__actions"><button class="primary" data-action="finish">おわる</button></div></section>`;}
function bindEvents(){app.querySelectorAll('[data-action]').forEach(e=>e.addEventListener('click',()=>handleAction(e.dataset)));const r=document.querySelector('#reflection');if(r)r.addEventListener('input',e=>state.reflection=e.target.value);if(state.screen==='work')setupWorkSurface();}
function setupWorkSurface(){const stage=document.querySelector('#stage'),svg=document.querySelector('#geometry-svg'),canvas=document.querySelector('#ink-canvas');resizeAndDrawInk(canvas);if(state.activeTool==='move'){svg.addEventListener('pointermove',e=>followCursor(e,svg));svg.addEventListener('pointerdown',e=>e.preventDefault());svg.addEventListener('pointerup',e=>{if(!e.defaultPrevented)placeDot();});}else canvas.addEventListener('pointerdown',e=>beginInkStroke(e,canvas));}
function followCursor(e,svg){if(state.activeTool!=='move')return;const r=svg.getBoundingClientRect(),q={x:clamp((e.clientX-r.left)*700/r.width,0,700),y:clamp((e.clientY-r.top)*460/r.height,0,460)},c=state.geometry.center,dx=q.x-c.x,dy=q.y-c.y,l=Math.hypot(dx,dy)||1,rad=distance(c,state.geometry.radiusPoint);state.geometry.radiusPoint={x:c.x+dx/l*rad,y:c.y+dy/l*rad};const a=svg.querySelector('.radius-arm'),h=svg.querySelector('.handle--radius');a.setAttribute('x2',state.geometry.radiusPoint.x);a.setAttribute('y2',state.geometry.radiusPoint.y);h.setAttribute('cx',state.geometry.radiusPoint.x);h.setAttribute('cy',state.geometry.radiusPoint.y);}
function remember(){state.history.push({geometry:copyGeometry(),dots:state.dots.map(d=>({...d})),strokes:state.strokes.length});if(state.history.length>20)state.history.shift();}
function placeDot(){const now=performance.now();if(now-state.lastPlacedAt<80)return;state.lastPlacedAt=now;const p=state.geometry.radiusPoint;if(state.dots.some(d=>distance(d,p)<22))return;remember();state.dots.push({x:p.x,y:p.y});if(state.dots.length>=18&&new Set(state.dots.map(d=>Math.floor((((Math.atan2(d.y-state.geometry.center.y,d.x-state.geometry.center.x)+Math.PI*2)%(Math.PI*2))/(Math.PI*2))*18))).size>=16)schedulePaletteChange();render();}
function schedulePaletteChange(){if(state.completionTimer)return;state.completionTimer=setTimeout(()=>{const choices=palettes.filter(p=>p.bg!==state.palette.bg);state.palette=choices[Math.floor(Math.random()*choices.length)];const r=95+Math.random()*75;state.geometry.radiusPoint={x:state.geometry.center.x+r,y:state.geometry.center.y};state.dots=[];state.completionTimer=null;render();},700);}
function beginInkStroke(e,c){e.preventDefault();remember();const st=[];const add=x=>{const r=c.getBoundingClientRect();st.push({x:x.clientX-r.left,y:x.clientY-r.top});drawInk(c,st)};add(e);c.setPointerCapture?.(e.pointerId);const move=x=>add(x);const up=()=>{state.strokes.push(st);window.removeEventListener('pointermove',move);render()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});}
function resizeAndDrawInk(c){const s=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=Math.max(1,r.width*s);c.height=Math.max(1,r.height*s);c.getContext('2d').setTransform(s,0,0,s,0,0);drawInk(c);}
function drawInk(c,current=[]){const x=c.getContext('2d'),r=c.getBoundingClientRect();x.clearRect(0,0,r.width,r.height);x.lineCap='round';x.lineWidth=4;x.strokeStyle='#24343b';[...state.strokes,current].forEach(st=>{if(!st.length)return;x.beginPath();st.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.stroke();});}
function undo(){const p=state.history.pop();if(!p)return;state.geometry=p.geometry;state.dots=p.dots;state.strokes=state.strokes.slice(0,p.strokes);render();}
function handleAction(d){switch(d.action){case'open-lesson':state.lesson=lessons.find(l=>l.id===d.lessonId)||lessons[0];state.screen='intro';break;case'go-home':state.screen='home';break;case'go-intro':state.screen='intro';break;case'start-work':state.screen='work';break;case'go-work':state.screen='work';break;case'go-summary':state.screen='summary';break;case'tool':state.activeTool=d.tool;break;case'undo':undo();return;case'open-help':state.helpOpen=true;break;case'close-help':state.helpOpen=false;break;case'finish':state.screen='home';break;default:return;}render();}
document.addEventListener('keydown',e=>{if(state.screen!=='work'||state.activeTool!=='move'||state.helpOpen||e.repeat)return;const safe=e.key==='Enter'||e.key===' '||e.code==='NumpadEnter'||(e.key.length===1&&!e.ctrlKey&&!e.metaKey&&!e.altKey);if(safe){e.preventDefault();placeDot();}});render();
